### PR TITLE
added cosign to pull public key from secrets

### PR DESCRIPTION
**Pull request by pxp928**
Good catch by @bradbeck. Using the cosign command to get the public key such that kyverno policy has the proper signing key for validation.

### CODE REVIEW

**Comment by pxp928** [comment]
Looks like i need to fix the integration test for this....one sec

**Comment by pxp928** [comment]
All set

**Review by bradbeck — DISMISSED** [review]

**Comment by bradbeck** [comment]
Although this will modify the `resources/kyverno/admission-control-policy/released/configmap-keys.json` file each time someone sets up a new minikube.

**Comment by mlieberman85** [comment]
> Although this will modify the `resources/kyverno/admission-control-policy/released/configmap-keys.json` file each time someone sets up a new minikube.

Should we add it to git ignore? I want to talk through some of this at the upcoming meeting.

**Comment by pxp928** [comment]
> > Although this will modify the `resources/kyverno/admission-control-policy/released/configmap-keys.json` file each time someone sets up a new minikube.
> 
> Should we add it to git ignore? I want to talk through some of this at the upcoming meeting.

Agree. That is what I was thinking to implement.

**Review by bradbeck — APPROVED** [review]

**Review by rgreinho — APPROVED** [review]
👍

**Pull request merged**
