### PR TITLE
Add vendor capability for spire quickstart

### PR DESCRIPTION
**Pull request by bradbeck**
Initial vendoring of the spire quickstart YAML's.

### CODE REVIEW

**Review by rgreinho — APPROVED** [review]
👍

**Comment by joshualucas84** [comment]
LGTM!

**Comment by mlieberman85** [comment]
Can you just pin to a commit? Something like:

```
QUICKSTART_COMMIT=1a5b67f24011599dd9f4c17cd23403a60841726a
QUICKSTART_URL="https://raw.githubusercontent.com/spiffe/spire-tutorials/$QUICKSTART_COMMIT/k8s/quickstart"
```

?

Anyone have thoughts on that? Just makes it easy when looking at this we know exactly what commit we pulled it in on?

**Comment by trmiller** [comment]
> Can you just pin to a commit? Something like:
> 
> ```
> QUICKSTART_COMMIT=1a5b67f24011599dd9f4c17cd23403a60841726a
> QUICKSTART_URL="https://raw.githubusercontent.com/spiffe/spire-tutorials/$QUICKSTART_COMMIT/k8s/quickstart"
> ```
> 
> ?
> 
> Anyone have thoughts on that? Just makes it easy when looking at this we know exactly what commit we pulled it in on?

For something where it's literally a dependency that we're pulling in - might be worth something similar to git externals ( though not literally that one ).

**Comment by bradbeck** [comment]
> Can you just pin to a commit? Something like:
> 
> ```
> QUICKSTART_COMMIT=1a5b67f24011599dd9f4c17cd23403a60841726a
> QUICKSTART_URL="https://raw.githubusercontent.com/spiffe/spire-tutorials/$QUICKSTART_COMMIT/k8s/quickstart"
> ```
> 
> ?
> 
> Anyone have thoughts on that? Just makes it easy when looking at this we know exactly what commit we pulled it in on?

Sure that make sense. Wasn't quite sure what to do in this chase since there are no "released" versions.

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Pull request merged**
