### PR TITLE
updated sample-pipeline and kyverno based on chains update. Added Sample-pipeline to integration test

### PR DESCRIPTION
**Pull request by pxp928**
Updated the sample-pipeline such that it can be deployed into the `prod` namespace. The Kyverno attestation checker policy will check that the image is signed and the provenance format matches. The integration test will help ensure that kyverno policy is always tested in each PR.

### CODE REVIEW

**Comment by pxp928** [comment]
Updates being made for kyverno Image also as there are cosign errors:
```
I0112 21:26:20.939475       1 imageVerify.go:171] EngineVerifyImages "msg"="verifying image" "kind"="Pod" "name"="ssf-lab-pipelinerun-jvbcm-build-and-push-image-8sw4j-pod-mdkp6" "namespace"="default" "policy"="verify-image" "image"="gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.29.0@sha256:66958b78766741c25e31954f47bc9fd53eaa28263506b262bf2cc6df04f18561"
I0112 21:26:21.677681       1 cosign.go:411] EngineVerifyImages "msg"="failed to extract image issuer from verification response" "kind"="Pod" "name"="ssf-lab-pipelinerun-jvbcm-build-and-push-image-8sw4j-pod-mdkp6" "namespace"="default" "policy"="verify-image" "image"="gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.29.0@sha256:66958b78766741c25e31954f47bc9fd53eaa28263506b262bf2cc6df04f18561" "payload"={"critical":{"identity":{"docker-reference":"gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint"},"image":{"docker-manifest-digest":"sha256:66958b78766741c25e31954f47bc9fd53eaa28263506b262bf2cc6df04f18561"},"type":"Tekton container signature"},"optional":{}}
I0112 21:26:21.678078       1 cosign.go:423] EngineVerifyImages "msg"="failed to extract image subject from verification response" "kind"="Pod" "name"="ssf-lab-pipelinerun-jvbcm-build-and-push-image-8sw4j-pod-mdkp6" "namespace"="default" "policy"="verify-image" "image"="gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.29.0@sha256:66958b78766741c25e31954f47bc9fd53eaa28263506b262bf2cc6df04f18561" "payload"={"critical":{"identity":{"docker-reference":"gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint"},"image":{"docker-manifest-digest":"sha256:66958b78766741c25e31954f47bc9fd53eaa28263506b262bf2cc6df04f18561"},"type":"Tekton container signature"},"optional":{}}
```

**Comment by pxp928** [comment]
> Updates being made for kyverno Image also as there are cosign errors:
> 
> ```
> I0112 21:26:20.939475       1 imageVerify.go:171] EngineVerifyImages "msg"="verifying image" "kind"="Pod" "name"="ssf-lab-pipelinerun-jvbcm-build-and-push-image-8sw4j-pod-mdkp6" "namespace"="default" "policy"="verify-image" "image"="gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.29.0@sha256:66958b78766741c25e31954f47bc9fd53eaa28263506b262bf2cc6df04f18561"
> I0112 21:26:21.677681       1 cosign.go:411] EngineVerifyImages "msg"="failed to extract image issuer from verification response" "kind"="Pod" "name"="ssf-lab-pipelinerun-jvbcm-build-and-push-image-8sw4j-pod-mdkp6" "namespace"="default" "policy"="verify-image" "image"="gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.29.0@sha256:66958b78766741c25e31954f47bc9fd53eaa28263506b262bf2cc6df04f18561" "payload"={"critical":{"identity":{"docker-reference":"gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint"},"image":{"docker-manifest-digest":"sha256:66958b78766741c25e31954f47bc9fd53eaa28263506b262bf2cc6df04f18561"},"type":"Tekton container signature"},"optional":{}}
> I0112 21:26:21.678078       1 cosign.go:423] EngineVerifyImages "msg"="failed to extract image subject from verification response" "kind"="Pod" "name"="ssf-lab-pipelinerun-jvbcm-build-and-push-image-8sw4j-pod-mdkp6" "namespace"="default" "policy"="verify-image" "image"="gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.29.0@sha256:66958b78766741c25e31954f47bc9fd53eaa28263506b262bf2cc6df04f18561" "payload"={"critical":{"identity":{"docker-reference":"gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint"},"image":{"docker-manifest-digest":"sha256:66958b78766741c25e31954f47bc9fd53eaa28263506b262bf2cc6df04f18561"},"type":"Tekton container signature"},"optional":{}}
> ```

Looks like these warning just needs to be suppressed. These will be fixed in later release.

**Review by bradbeck — APPROVED** [review]

**Comment by pxp928** [comment]
Looks like the spire update broke this integration test. I will update

**Comment by pxp928** [comment]
Fixed Integration Test

**Review by bradbeck — DISMISSED** [review]

**Review by rgreinho — APPROVED** [review]
👍

**Pull request merged**
