### PR TITLE
Remove template twitter handle

### PR DESCRIPTION
**Pull request by trmiller**
Given this both links to the twitter handle of the theme creater, and we don't have a twitter account for SSF anyway, removing.

### CODE REVIEW

**Review by rgreinho — CHANGES_REQUESTED** [review]
We are not supposed to edit the theme directly. Everything should be configurable via the `config.toml` file.

For instance in this case, I believe this could be what we are looking for: https://github.com/aaranxu/adidoks/blob/137d6186dc24d1582098fb13aa65e4e38ec36a76/config.toml.example#L82

**Comment by rgreinho** [comment]
If you add the following section to the `config.toml` file it should to the trick:

```toml
[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/thesecuresoftwarefactory/ssf"
post = "v0.1.0"
weight = 20
```

**Comment by rgreinho** [comment]
Also, this made me notice a CI problem. The "Install SSF" workflow does not run when there are only changes in the documentation, but since it is marked as required in the branch protection, this PR will never merge.

To solve this, you could remove the `paths-ignore` section in the workflow file (https://github.com/thesecuresoftwarefactory/ssf/blob/main/.github/workflows/install-ssf.yaml#L8-L9).

**Comment by trmiller** [comment]
going to kill this & re-do.  but @rgreinho noted on the documentation PR issue.

**Pull request closed without merging**
