### PR TITLE
Fix linting errors

### PR DESCRIPTION
**Pull request by rgreinho**
Fixes the linting errors that were not previously addressed.

The `Makefile` targets were adjusted or corrected to fit our needs and
integrated into our CI workflow. The configuration files were also
updated accordingly.

A new task was added to automatically reformat markdown files using
`prettier`.

### CODE REVIEW

**Comment by rgreinho** [comment]
It also fixes all the CI violations. ✅

**Comment by bradbeck** [comment]
Are we sure we want to be modifying the files in `docs/themes/adidoks`? I was under the impression that these were vendored.

**Comment by rgreinho** [comment]
> Are we sure we want to be modifying the files in `docs/themes/adidoks`? I was under the impression that these were vendored.

They are not really vendored, they are just there because I dislike using submodules (which is the recommended approach). So I copy pasted the theme instead. 

But we can totally create a `.prettierignore` file and add this folder to it if you'd want.

**Comment by rgreinho** [comment]
@bradbeck And done ✅

**Review by bradbeck — APPROVED** [review]

**Review by mlieberman85 — APPROVED** [review]

**Pull request merged**
