### PR TITLE
CI build badge status for README

### PR DESCRIPTION
**Pull request by joshualucas84**

### CODE REVIEW

**Review by bradbeck — DISMISSED** [review]

**Review by rgreinho — COMMENTED** [review]
I am not against the idea of having a CI badge, but then it will appear on the documentation site as well and I am not sure it fits there.

image

**Comment by joshualucas84** [comment]
> I am not against the idea of having a CI badge, but then it will appear on the documentation site as well and I am not sure it fits there.
> 
> image

Ahh I didnt think about that how that would look in the doc page, maybe the badge needs to be in the footer.

**Comment by rgreinho** [comment]
Definitely looks better, but still a bit lonely

image

Maybe we could add more relevant badges? Or something to make it a more appealing footer?

**Comment by sudo-bmitch** [comment]
I'd be inclined to make the docs not have a pointer to the top level readme, and instead have the readme point to the docs where needed.

**Pull request closed without merging**
