### PR TITLE
Refactor grype task

### PR DESCRIPTION
**Pull request by bradbeck**
Refactor the grype task to directly execute rather than running a script.

### CODE REVIEW

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Review by rgreinho — COMMENTED** [review]
YES! 👍 

Would you be ok to move it up one level, in the "examples.cue" file? Otherwise #163 will not benefit from this update.

**Comment by bradbeck** [comment]
> YES! 👍
> 
> Would you be ok to move it up one level, in the "examples.cue" file? Otherwise #163 will not benefit from this update.

@rgreinho Do you need any of the tasks other than `grype-vulnerability-scan` pulled up?

**Comment by rgreinho** [comment]
Nope, just that one would be fine. 👍

**Review by pxp928 — APPROVED** [review]

**Pull request merged**
